export const ORDER_AMOUNT_CHANGE = 'ORDER_AMOUNT_CHANGE';
export const ORDER_CCYPAIR_CHANGE = 'ORDER_CCYPAIR_CHANGE';
export const ORDER_BOOK = 'ORDER_BOOK';
export const ORDER_BOOKING_COMPLETE = 'ORDER_BOOKING_COMPLETE';